# Generated by Django 4.2.3 on 2023-08-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project', '0002_user_points_alter_user_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='use', max_length=16),
        ),
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='post',
            name='kanji',
            field=models.CharField(max_length=32),
        ),
    ]
