# Generated by Django 4.2.3 on 2023-08-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(upload_to='user_profile_pics'),
        ),
    ]
